"""
Azure Architecture Diagram: infraops-static-demo
Generated by diagram agent
Date: 2026-01-20

Prerequisites:
- pip install diagrams
- Graphviz installed (choco install graphviz / brew install graphviz / apt-get install graphviz)

Generate PNG: python 03-des-diagram.py
"""

from diagrams import Diagram, Cluster, Edge
from diagrams.azure.network import FrontDoors, VirtualNetworks
from diagrams.azure.compute import AppServices
from diagrams.azure.devops import ApplicationInsights
from diagrams.c4 import Container
from diagrams.onprem.vcs import Github

# Diagram configuration
graph_attr = {
    "fontsize": "20",
    "bgcolor": "white",
    "pad": "1.0",
    "rankdir": "TB"
}

with Diagram(
    "infraops-static-demo Architecture",
    show=False,
    direction="TB",
    filename="03-des-diagram",
    graph_attr=graph_attr
):
    # External source
    github = Github("GitHub Repository\n(React + Vite)")

    with Cluster("CI/CD Pipeline"):
        actions = Container("GitHub Actions", "Auto Deploy")

    github >> Edge(label="Push Code", fontsize="10") >> actions

    with Cluster("Azure Region - West Europe"):
        with Cluster("Static Web App (Standard)"):
            swa_prod = AppServices("Production App")
            swa_staging = AppServices("Staging Environments")

        cdn = FrontDoors("Global CDN\n(118+ Edge Locations)")
        swa_prod >> Edge(label="", fontsize="10") >> cdn
        swa_staging >> Edge(label="Preview URLs", fontsize="10") >> cdn

        with Cluster("Monitoring & Observability"):
            app_insights = ApplicationInsights("Application Insights")

        swa_prod >> Edge(label="Telemetry", fontsize="10") >> app_insights

    actions >> Edge(label="Deploy", fontsize="10") >> swa_prod

    # Global users
    users = Github("Global Users")
    cdn >> Edge(label="HTTPS + Cached Assets", fontsize="10") >> users

    with Cluster("Features Included"):
        features = Container(
            "Features", "✓ Managed SSL\n✓ Auto-Deploy\n✓ Staging Slots\n✓ Custom Auth")
