// ============================================================================
// main.bicepparam - infraops-static-demo
// Parameter file for Static Web App with Application Insights deployment
// Generated by bicep-implement agent | 2026-01-20
// ============================================================================

using 'main.bicep'

// ============================================================================
// Deployment Parameters
// ============================================================================

// Azure region for deployment (EU data residency compliant)
param location = 'westeurope'

// Target environment
param environment = 'prod'

// Project identifier for resource naming
param projectName = 'infraops-static-demo'

// Owner for tagging and accountability
param owner = 'infraops-team'

// Cost center for billing allocation
param costCenter = 'demo'
