// ============================================================================
// main.bicep - infraops-static-demo
// Static Web App with Application Insights telemetry
// Generated by bicep-implement agent | 2026-01-20
// ============================================================================

targetScope = 'resourceGroup'

// ============================================================================
// Parameters
// ============================================================================

@description('Azure region for resource deployment')
@allowed([
  'westeurope'
  'swedencentral'
  'germanywestcentral'
  'northeurope'
])
param location string = 'westeurope'

@description('Environment name')
@allowed([
  'dev'
  'staging'
  'prod'
])
param environment string = 'prod'

@description('Project name used for resource naming')
@minLength(3)
@maxLength(24)
param projectName string = 'infraops-static-demo'

@description('Owner team or individual')
param owner string = 'infraops-team'

@description('Cost center for billing')
param costCenter string = 'demo'

// ============================================================================
// Variables
// ============================================================================

// Region abbreviations for CAF naming
var regionAbbreviations = {
  westeurope: 'weu'
  swedencentral: 'swc'
  germanywestcentral: 'gwc'
  northeurope: 'neu'
}
var locationAbbrev = regionAbbreviations[location]

// Unique suffix for globally unique resource names (available for child modules if needed)
#disable-next-line no-unused-vars
var uniqueSuffix = uniqueString(resourceGroup().id)

// Naming convention following CAF pattern
var logAnalyticsName = 'log-${projectName}-${environment}-${locationAbbrev}'
var appInsightsName = 'appi-${projectName}-${environment}-${locationAbbrev}'
var staticWebAppName = 'stapp-${projectName}-${environment}'

// Required tags for all resources (WAF: Operational Excellence)
var tags = {
  Environment: environment
  ManagedBy: 'Bicep'
  Project: projectName
  Owner: owner
  CostCenter: costCenter
}

// ============================================================================
// Modules
// ============================================================================

// Log Analytics Workspace - Centralized observability (WAF: Reliability, Operations)
module logAnalytics 'modules/log-analytics.bicep' = {
  name: 'log-analytics-deployment'
  params: {
    name: logAnalyticsName
    location: location
    tags: tags
    retentionInDays: 30
  }
}

// Application Insights - Workspace-based telemetry (WAF: Reliability, Operations)
module appInsights 'modules/app-insights.bicep' = {
  name: 'app-insights-deployment'
  params: {
    name: appInsightsName
    location: location
    tags: tags
    workspaceResourceId: logAnalytics.outputs.resourceId
  }
}

// Static Web App - React SPA hosting (WAF: Performance, Reliability)
module staticWebApp 'modules/static-web-app.bicep' = {
  name: 'static-web-app-deployment'
  params: {
    name: staticWebAppName
    location: location
    tags: tags
    appInsightsConnectionString: appInsights.outputs.connectionString
    appInsightsInstrumentationKey: appInsights.outputs.instrumentationKey
  }
}

// ============================================================================
// Outputs
// ============================================================================

@description('Log Analytics Workspace resource ID')
output logAnalyticsWorkspaceId string = logAnalytics.outputs.resourceId

@description('Log Analytics Workspace name')
output logAnalyticsWorkspaceName string = logAnalytics.outputs.name

@description('Application Insights resource ID')
output appInsightsId string = appInsights.outputs.resourceId

@description('Application Insights name')
output appInsightsName string = appInsights.outputs.name

@description('Application Insights instrumentation key')
output appInsightsInstrumentationKey string = appInsights.outputs.instrumentationKey

@description('Static Web App resource ID')
output staticWebAppId string = staticWebApp.outputs.resourceId

@description('Static Web App name')
output staticWebAppName string = staticWebApp.outputs.name

@description('Static Web App default hostname')
output staticWebAppDefaultHostname string = staticWebApp.outputs.defaultHostname

@description('Static Web App URL')
output staticWebAppUrl string = 'https://${staticWebApp.outputs.defaultHostname}'
